apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeserver
  labels:
    app: nodeserver
spec:
  selector:
    matchLabels:
      app: nodeserver
  replicas: 2
  template:
    metadata:
      name: nodeserver
      labels:
        app: nodeserver
    spec:
      containers:
        - name: nodeserver
          image: andradereginaldo/node_k8s:1.2.1
          envFrom:
            - configMapRef:
                name: nodeserver-env
          # env:
          #   - name: NAME
          #     valueFrom:
          #       configMapKeyRef:
          #         name: nodeserver-env
          #         key: NAME
          #   - name: AGE
          #     valueFrom:
          #       configMapKeyRef:
          #         name: nodeserver-env
          #         key: AGE
