apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeserver
  labels:
    app: nodeserver
spec:
  selector:
    matchLabels:
      app: nodeserver
  replicas: 1
  template:
    metadata:
      name: nodeserver
      labels:
        app: nodeserver
    spec:
      containers:
        - name: nodeserver
          image: andradereginaldo/node_k8s:3.1
          resources:
            requests:
              cpu: 250m
              memory: 100Mi
            limits:
              cpu: 500m
              memory: 150Mi
          envFrom:
            - configMapRef:
                name: nodeserver-env
            - secretRef:
                name: nodeserver-secret
